### ISSUE TITLE
Hi, I can't download on a mac

### ISSUE THREAD

**Issue by Fishtang01** [cove9988/TradingGym#3]
Hi, I can't download.  I use a mac.  I need your help. here is my error message:

Pauls-MacBook-Pro:~ paul$ pip3 install https://github.com/cove9988/TradingGym.git
Collecting https://github.com/cove9988/TradingGym.git
  Downloading https://github.com/cove9988/TradingGym.git
     / 81kB 467kB/s
  Cannot unpack file /private/var/folders/bd/d0vxwn3j5rnfjwnsgy0wp0300000gn/T/pip-wtngrslj-unpack/TradingGym.git (downloaded from /private/var/folders/bd/d0vxwn3j5rnfjwnsgy0wp0300000gn/T/pip-6v70569e-build, content-type: text/html; charset=utf-8); cannot detect archive format
Cannot determine archive format of /private/var/folders/bd/d0vxwn3j5rnfjwnsgy0wp0300000gn/T/pip-6v70569e-build

**Comment by zbanga** [comment]
Seems like you're trying to run the wrong command, the correct command is

pip3 install git+https://github.com/cove9988/TradingGym.git

**Comment by Fishtang01** [comment]
HI zbanga, thank you for the answer.  I am new to python, and learning about this is like climbing a cliff hanger.  I need to ask, read and learn everything line of codes.  thanks again for your help.

**Comment by cove9988** [comment]
Thanks, @zbanga
