### ISSUE TITLE
源码安装失败

### ISSUE THREAD

**Issue by HaveF** [cove9988/TradingGym#5]
感谢repo

`python setup.py install`
https://github.com/cove9988/TradingGym/blob/master/envs/trading.py#L240

这一行好像错了哦
上面一行还是for呢, 这一行就直接是class了

另外有群加吗, 群的二维码过期了

谢谢!

**Comment by cove9988** [comment]
好像· setup.py   不工作，我没有群，谁有我们加一个吧，
